import Head from 'next/head';
import Link from 'next/link';
import Header from 'src/parts/Header';
import Hero from 'src/parts/Hero';
import Features from 'src/parts/Features';
import ListCourses from 'src/parts/ListCourses';
import ListCategories from 'src/parts/ListCategories';
import Footer from 'src/parts/Footer';
import ApiCourses from 'src/constans/api/ApiCourses';

function Home({ data }) {
  return (
    <>
      <Head>
        <title>C-Learn</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="bg-background">
        <section className="header-clipping pt-8 bg-backgroundd">
          <div className="container mx-auto px-20">
            <Header></Header>
            <Hero></Hero>
          </div>
        </section>
        <section className="container mx-auto pt-24 px-20 ">
          <Features></Features>
        </section>
        <section className="container mx-auto pt-24 px-20">
          <ListCourses data={data}></ListCourses>
        </section>
        <section className="container mx-auto pt-24 px-20">
          <ListCategories></ListCategories>
        </section>
        <footer className="mt-24  bg-secondary mx-auto py-12 px-20">
          <Footer></Footer>
        </footer>
      </main>
    </>
  );
}

Home.getInitialProps = async () => {
  try {
    const data = await ApiCourses.all();
    return data;
  } catch (error) {
    return error;
  }
};
export default Home;
